language: java
install: true
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: "levry-github"
    token:
      secure: DU7ydIzioDab7HQUF1C9mhkKRfTn5Pq1RIQ7Nor9P5eV61AlDQIL6iKEAdyjmBAsfdNgXGOlxFjpVr6AN95gLcjXiopaaL2GPMV04SS/D4o2dW/dDJyHydLkUZYbppFn/TARYc9OtAHEObFgMU+m5PrHqLaKLAkjlhLysFGMgQ29zVZpeTlB5UaxD21upEj79E1kjSqkFilOZohOafw99gqcaVPCRQLxLdIxp84Hz/gPepaeVoKGzH8TK/SOF2hh9pQntMv9kHIt8XBnTOtOkCrGSlP+df/OYeFqt4R6Nt5nZmww9VJCp1r3CHcHCNDkzeJFjMIybRj5Bul+DUOyNIyHtbwfH2K2o5ZqaBDHCnWPOq6VxMcVcXxBeyT51SuGGdc0o9oonMYstgethnO++19HyuZ44K9zA5t2Csu4iNjOU8BenlLYWCH7O6sSOq0XejUELwIy8S7ICqsK3f91453MjaQwWwJ3CLC+g9bw9iMixLTG/dsh3meErW8NHe5gE3xVn+Ki87pmomx7LFVnwdNF5Kp8zuDAb1Yn102UeJcTH4WxvQyCTZaTJnBHxZ5XSId/WG3fexFWsc6pB0f/5I8KIZh/k3x4xd1rF/9UsEJMwI9ps6hGKE2AExRO5Zj5hikgRcraleiOKiHfrIFRnjIZ4CSvQE6YhMjXQtFOW7E=
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache
before_install:
  - chmod +x gradlew

jobs:
  include:
    - stage: test
      script:
        - ./gradlew check --console=plain
        - ./gradlew jacocoTestReport --console=plain
        - ./gradlew sonarqube --console=plain
    - stage: publish
      script:
        - ./gradlew assemble -x check
        - ./gradlew bintrayUpload --console=plain
      env:
        - secure: aQnw1mCDlo8fwhVefKisVgqnmDvG7auzjvsoOtMGPoI9ajf27yq69w32ZJ+uSysNCTFwa30J4cGQYq/N+zT/E7XgEqEnA3xjZfUZkpGqABUR//Pgb9JFR5xKzmojNQ6bPpKRR9HKKs7/Bpl8a1B112dMQo/YzMNu6Md3O2Fqoq3OQ728OZdEAoRfyoMMUEqqoizR0VugnZXZC2bmmQrVG+l2Ye+WvVIF1n/eRwh4NScewbbVfQr7+tuN+0cDwcQl+YH5uQxgd1VhXo+OGNhrf3w8exbkVTvXJaaitPJ6kGb1OTux9z/fpmp0x8QOcmpH0dWzczlXZI1auECL1OBlTze5RVHLMvldAsxtfhrrgkz9iMwfwLp2HJPvZICZYEZiXXRhYMqar0xubOKBOmsqWB+HiZXxQZn2aXgFvoqZ+d7oLVpjwpTXAuVl2VoFi/lp5d3v3EAsy+atNv6T+HWgGJ30+ecJQpZY+vNHkfuN2f7OXAW/qXT84TnfIddSRRWE9wqkI4uUkw820ELZhks9OmrOEre4rnkpxG29kYNfYSY7wsWAZ0VGh6ZXF+X4d2dzhOuB1TOcAG7/Nmv8iD1j5xE+G6wmJJJxotxiIHzyVVYAKvmeR9VCqIsS1ny0LoZsiqBqhv71ajfIP7TXt3DTuboaVp18uWIygxmCvLBbsIM=
      if: branch = master

branches:
  only:
    - master
    - develop